In [9]:
import pandas as pd
df = pd.read_csv('pregunta5.csv')
df.keys()

Index(['id', 'casado', 'tiene_hijos', 'nro_dpntes', 'edad', 'trabaja',
       'tipo_vivienda', 'hace_deporte', 'ofrece_seguro'],
      dtype='object')

In [10]:
print('Dataframe')
print(df)

Dataframe
     id casado tiene_hijos  nro_dpntes  edad trabaja tipo_vivienda  \
0   701     no          si           1    25      si        propia
1   305     no          no           0    29      no      familiar
2   203     no          si           1    34      si        propia
3   304     si          si           3    43      si        propia
4   102     si          no           1    51      si        propia
5   406     si          si           2    52      si      arrienda
6   507     si          si           4    43      si      arrienda
7   108     no          no           0    33      no      familiar
8   409     si          si           1    27      si        propia
9   180     si          si           1    28      si        propia
10  191     si          no           2    50      si      familiar
11  212     no          si           1    34      si      familiar
12  213     si          si           1    42      si      familiar
13  314     si          no           1    40      no      arrienda
14  415     si          si           1    25      si        propia
15  116     si          no           0    39      no      familiar
16  117     si          no           1    31      si        propia
17  218     no          no           0    37      si        propia
18  519     no          si           1    29      si      familiar
19  120     si          si           1    30      si        propia
20  221     si          no           0    28      si      familiar
21  322     no          si           1    27      si        propia
22  323     si          si           4    40      si        propia
23  624     no          si           1    36      si        propia
24  125     si          no           0    39      no      familiar

    hace_deporte       ofrece_seguro
0              1  si con condiciones
1              0                  no
2              0                  si
3              1                  si
4              2  si con condiciones
5              0                  no
6              3                  si
7              0                  no
8              2                  si
9              3  si con condiciones
10             0                  no
11             2                  si
12             0                  no
13             0                  no
14             0                  si
15             0                  no
16             2  si con condiciones
17             3  si con condiciones
18             3                  si
19             0                  si
20             1  si con condiciones
21             3  si con condiciones
22             1                  si
23             3                  si
24             1                  no

In [11]:
df = pd.get_dummies(df, columns = ["trabaja"], drop_first = True)

In [12]:
viviendas = {"propia":0,"familiar":1,"arrienda":2}
df['vivienda'] = df['tipo_vivienda'].replace(viviendas)
seguros = {"si con condiciones": 1, "no":0, "si":2}
df['ofrece_seguro'] = df['ofrece_seguro'].replace(seguros)
df

,id,casado,tiene_hijos,nro_dpntes,edad,tipo_vivienda,hace_deporte,ofrece_seguro,trabaja_si,vivienda
0,701,no,si,1,25,propia,1,1,1,0
1,305,no,no,0,29,familiar,0,0,0,1
2,203,no,si,1,34,propia,0,2,1,0
3,304,si,si,3,43,propia,1,2,1,0
4,102,si,no,1,51,propia,2,1,1,0
5,406,si,si,2,52,arrienda,0,0,1,2
6,507,si,si,4,43,arrienda,3,2,1,2
7,108,no,no,0,33,familiar,0,0,0,1
8,409,si,si,1,27,propia,2,2,1,0
9,180,si,si,1,28,propia,3,1,1,0
10,191,si,no,2,50,familiar,0,0,1,1
11,212,no,si,1,34,familiar,2,2,1,1
12,213,si,si,1,42,familiar,0,0,1,1
13,314,si,no,1,40,arrienda,0,0,0,2
14,415,si,si,1,25,propia,0,2,1,0
15,116,si,no,0,39,familiar,0,0,0,1
16,117,si,no,1,31,propia,2,1,1,0
17,218,no,no,0,37,propia,3,1,1,0
18,519,no,si,1,29,familiar,3,2,1,1
19,120,si,si,1,30,propia,0,2,1,0
20,221,si,no,0,28,familiar,1,1,1,1
21,322,no,si,1,27,propia,3,1,1,0
22,323,si,si,4,40,propia,1,2,1,0
23,624,no,si,1,36,propia,3,2,1,0
24,125,si,no,0,39,familiar,1,0,0,1

In [13]:
df = pd.get_dummies(df, columns = ["tiene_hijos"], drop_first = True)
df = pd.get_dummies(df, columns = ["casado"], drop_first = True)

In [14]:
df.drop(['tipo_vivienda'], axis=1, inplace=True)
df.drop(['id'], axis=1, inplace=True)

In [15]:
df

,nro_dpntes,edad,hace_deporte,ofrece_seguro,trabaja_si,vivienda,tiene_hijos_si,casado_si
0,1,25,1,1,1,0,1,0
1,0,29,0,0,0,1,0,0
2,1,34,0,2,1,0,1,0
3,3,43,1,2,1,0,1,1
4,1,51,2,1,1,0,0,1
5,2,52,0,0,1,2,1,1
6,4,43,3,2,1,2,1,1
7,0,33,0,0,0,1,0,0
8,1,27,2,2,1,0,1,1
9,1,28,3,1,1,0,1,1
10,2,50,0,0,1,1,0,1
11,1,34,2,2,1,1,1,0
12,1,42,0,0,1,1,1,1
13,1,40,0,0,0,2,0,1
14,1,25,0,2,1,0,1,1
15,0,39,0,0,0,1,0,1
16,1,31,2,1,1,0,0,1
17,0,37,3,1,1,0,0,0
18,1,29,3,2,1,1,1,0
19,1,30,0,2,1,0,1,1
20,0,28,1,1,1,1,0,1
21,1,27,3,1,1,0,1,0
22,4,40,1,2,1,0,1,1
23,1,36,3,2,1,0,1,0
24,0,39,1,0,0,1,0,1

In [16]:
import numpy as np
X = np.array(df.drop(['ofrece_seguro'],1))
y = np.array(df['ofrece_seguro'])
X.shape

(25, 7)

In [25]:
from sklearn import linear_model
from sklearn import model_selection
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt
import seaborn as sb
%matplotlib inline

model = linear_model.LogisticRegression(multi_class='auto')
model.fit(X,y)

C:\Users\QUIPU-INV04-19\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [26]:
predictions = model.predict(X)
predictions

array([2, 0, 2, 2, 1, 0, 2, 0, 2, 1, 0, 2, 0, 0, 2, 0, 1, 1, 2, 2, 1, 2,
       2, 1, 0], dtype=int64)

In [27]:
model.score(X,y)

0.88

In [28]:
# VALIDACIÓN DEL MODELO
"""
Una buena práctica en Machine Learning es la de subdividir nuestro conjunto de datos de entrada 
en un set de entrenamiento y otro para validar el modelo (que no se utiliza durante el entrenamiento 
y por lo tanto la máquina desconoce).
"""
validation_size = 0.20
seed = 7
X_train, X_validation, Y_train, Y_validation = model_selection.train_test_split(X, y, test_size=validation_size, random_state=seed)

In [29]:
name='Logistic Regression'
kfold = model_selection.KFold(n_splits=10, random_state=seed)
cv_results = model_selection.cross_val_score(model, X_train, Y_train, cv=kfold, scoring='accuracy')
msg = "%s: %f (%f)" % (name, cv_results.mean(), cv_results.std())
print(msg)

Logistic Regression: 0.650000 (0.390512)

C:\Users\QUIPU-INV04-19\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\QUIPU-INV04-19\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\QUIPU-INV04-19\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\QUIPU-INV04-19\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\QUIPU-INV04-19\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\QUIPU-INV04-19\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\QUIPU-INV04-19\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\QUIPU-INV04-19\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\QUIPU-INV04-19\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\QUIPU-INV04-19\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

In [30]:
predictions = model.predict(X_validation)
print(accuracy_score(Y_validation, predictions))

1.0

In [31]:
# MAtriz de confusión
print(confusion_matrix(Y_validation, predictions))

[[3 0]
 [0 2]]

In [32]:
print(classification_report(Y_validation, predictions))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         3
           2       1.00      1.00      1.00         2

    accuracy                           1.00         5
   macro avg       1.00      1.00      1.00         5
weighted avg       1.00      1.00      1.00         5